-- Principais serviços adicionais (busca na home + cadastro de prestador).
insert into public.service_areas (slug, name) values
  ('desentupidor', 'Desentupidor'),
  ('marido_aluguel', 'Marido de aluguel'),
  ('vidraceiro', 'Vidraceiro'),
  ('cuidador', 'Cuidador de pessoas'),
  ('gesso_drywall', 'Gesso e drywall'),
  ('eletrodomesticos', 'Assistência eletrodomésticos'),
  ('baba', 'Babá'),
  ('serralheria', 'Serralheria e solda'),
  ('redes_cabeamento', 'Cabeamento e redes'),
  ('desenvolvimento', 'Sites e sistemas'),
  ('seguranca_eletronica', 'Segurança eletrônica'),
  ('cozinheira', 'Cozinheira'),
  ('manicure', 'Manicure e pedicure'),
  ('personal_trainer', 'Personal trainer'),
  ('cabeleireiro', 'Cabeleireiros'),
  ('nutricionista', 'Nutricionista'),
  ('dedetizador', 'Dedetizador'),
  ('motorista', 'Motorista'),
  ('arquiteto', 'Arquitetos'),
  ('marketing', 'Marketing online'),
  ('aulas_idiomas', 'Aula de idiomas'),
  ('passadeira', 'Passadeira'),
  ('redes_protecao', 'Redes de proteção'),
  ('psicologo', 'Psicólogo'),
  ('contador', 'Contador'),
  ('tapeceiro', 'Tapeceiro'),
  ('bartender', 'Bartenders'),
  ('audio_video', 'Áudio e vídeo'),
  ('engenheiro', 'Engenheiro')
on conflict (slug) do nothing;
